version: 2.1
# Use a package of configuration called an orb.
jobs:
# Sequential workflow
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name myStack
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure